DROP TABLE INSA_CARRIER_SEQ CASCADE CONSTRAINTS;
DROP TABLE INSA_ACAD_ABILITY_SEQ CASCADE CONSTRAINTS;
DROP TABLE INSA_INPUT_INFO_SEQ CASCADE CONSTRAINTS;
DROP TABLE INSA_COM_SEQ CASCADE CONSTRAINTS;
DROP TABLE INSA CASCADE CONSTRAINTS;

DROP SEQUENCE INSA_CARRIER_SEQ;
DROP SEQUENCE INSA_ACAD_ABILITY_SEQ;
DROP SEQUENCE INSA_INPUT_INFO_SEQ;
DROP SEQUENCE INSA_COM_SEQ;
DROP SEQUENCE INSA_SEQ;

DROP TABLE INSA_CARRIER;
DROP TABLE INSA_ACAD_ABILITY;
DROP TABLE INSA_INPUT_INFO;
DROP TABLE INSA_COM;
DROP TABLE INSA;

