-- DROP TABLE INSA_CARRIER CASCADE CONSTRAINTS;

-- SELECT * FROM INSA_CARRIER;

DROP SEQUENCE INSA_CARRIER_SEQ;
CREATE SEQUENCE INSA_CARRIER_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;

DROP TABLE INSA_CARRIER;
CREATE TABLE INSA_CARRIER(
	SABUN NUMBER, -- 사번
	SEQ NUMBER PRIMARY KEY, -- 일련번호
	CMP_NAME_CARRIER VARCHAR2(50), -- 회사명
	WORK_START_DAY DATE, -- 근무시작일
	WORK_END_DAY DATE, -- 근무종료일
	POS_GBN_CODE VARCHAR2(50), -- 직위
	RESPON_DEPT VARCHAR2(50), -- 담당업무
	WORK_CONTENTS VARCHAR2(500), -- 근무내용
	FOREIGN KEY (SABUN) REFERENCES INSA (SABUN) ON DELETE CASCADE
);