-- DROP TABLE INSA_INPUT_INFO CASCADE CONSTRAINTS;

-- SELECT * FROM INSA_INPUT_INFO;

DROP SEQUENCE INSA_INPUT_INFO_SEQ;
CREATE SEQUENCE INSA_INPUT_INFO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;

DROP TABLE INSA_INPUT_INFO;
CREATE TABLE INSA_INPUT_INFO(
	SABUN NUMBER, -- 사번
	SEQ NUMBER PRIMARY KEY, -- 일련번호
	WRK_POSB_DAY DATE, -- 근무가능일
	SUGST_MONEY NUMBER, -- 월제시금액
	PJT_GBN_CODE VARCHAR2(50), -- PJ형태구분코드
	EQM_YN VARCHAR2(20), -- 장비유무
	CURRENT_SALARY NUMBER, -- 현재연봉
	WORK_AREA VARCHAR2(50), -- 근무지
	FOREIGN KEY (SABUN) REFERENCES INSA (SABUN) ON DELETE CASCADE
);