-- DROP TABLE INSA_ACAD_ABILITY CASCADE CONSTRAINTS;

-- SELECT * FROM INSA_ACAD_ABILITY;

DROP SEQUENCE INSA_ACAD_ABILITY_SEQ;
CREATE SEQUENCE INSA_ACAD_ABILITY_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;

DROP TABLE INSA_ACAD_ABILITY;
CREATE TABLE INSA_ACAD_ABILITY(
	SABUN NUMBER, -- 사번
	SEQ NUMBER PRIMARY KEY, -- 일련번호
	MAJOR_STUD_GBN VARCHAR2(50), -- 전공구분
	GART_LEVEL VARCHAR2(50), -- 졸업여부
	GART_YEAR NUMBER, -- 졸업년
	GART_MONTH NUMBER, -- 졸업월
	SCHOOL_NAME VARCHAR2(50), -- 학교명
	FOREIGN KEY (SABUN) REFERENCES INSA (SABUN) ON DELETE CASCADE
);